### PR TITLE
Add custom prefix support

### LINKED ISSUE #62: Update readme with new options parameter
Readme still has Boolean instead of options Object as the second parameter

### LINKED ISSUE #65: Picostyle is incompatible with Preact 10
Cross posting this from an issue I raised here: https://github.com/preactjs/enzyme-adapter-preact-pure/issues/61

Picostyle expects the render function to be called with the second argument being the children of the component, not the context, this should be an element, string or array. An invalid VNode is created because of this.

full comment describing the issue here: https://github.com/preactjs/enzyme-adapter-preact-pure/issues/61#issuecomment-508912849

### PR DESCRIPTION
**Pull request by B-Teague**
Closes #62 
Closes #65

Adds new custom prefix support for easier debugging.
A global custom prefix can be defined in the options parameter:
```
const options = {
   returnObject: true,
   prefix: "customGlobalPrefix"
}
```
Each class can have it's own custom prefix using the css function
```js
css({color:orange}, "thisComponentsPrefix")
```

### CODE REVIEW

**Comment by B-Teague** [comment]
This change breaks the size limit. Do you want to increase the size limit to 1k?

**Comment by msaktype** [comment]
@B-Teague Wow, good catch 👍 

> Do you want to increase the size limit to 1k?

Sure.

**Comment by B-Teague** [comment]
Sorry, I no longer have time to work on this.  Please feel free to clone these changes and merge.

**Comment by B-Teague** [comment]
Have some time to work on this again.

**Comment by B-Teague** [comment]
Morishitter, this pull request is ready for your review.

**Key changes:**  
1. Changed return function (attributes, children) to function(props) to match the render function in react and preact for issue #65
2. Add prefix support to css and picostyle functions. (Do I need to add this for keyframes?  Also, does keyframes need caching?)
3. Rename parse to serialize.  This library is converting an in-memory javascript object to a CSS string (serialization)
4. Project cleanup - Updated several dependency versions.  Removed yarn.  Ran npm audit fix to address a security vulnerability.  Removed size-limit (newer versions try to download Chrome).  Created package-lock.json, so packages can be installed using `npm ci`

**Pull request closed without merging**
